import numpy as np
import pandas as pd
from scipy import stats


In [1]:
import pandas as pd

In [1]:
df=pd.read_csv("C:\\Users\\Akshata Pandit\\OneDrive\\vscode1\\fuzzy projects\\alzheimer.csv")

NameError: name 'pd' is not defined

In [ ]:
df


In [ ]:
df.describe()

In [ ]:


df.shape

In [ ]:
df.info

In [ ]:
df.head(10)

# Attributes explaination

Group --> Class
<br>
Age --> Age
<br>
EDUC --> Years of Education
<br>
SES --> Socioeconomic Status / 1-5
<br>
MMSE --> Mini Mental State Examination
<br>
CDR --> Clinical Dementia Rating
<br>
eTIV --> Estimated total intracranial volume
<br>
nWBV --> Normalize Whole Brain Volume
<br>
ASF --> Atlas Scaling Factor

CDR: This is the target variable, not a feature for prediction.
MMSE: Directly measures cognitive function, crucial for Alzheimer's diagnosis.
eTIV, nWBV, ASF: Brain structural measures, highly relevant to Alzheimer's disease.
Age: A strong risk factor for Alzheimer's.
EDUC: Potentially correlated with cognitive function and disease progression.
SES: Might have some influence, but likely less direct than other features.
Group: While potentially informative, it might be dependent on other factors and could introduce bias.

In [ ]:
df.isnull().sum()

In [ ]:
df['SES']=df['SES'].ffill()

In [ ]:
df['MMSE']=df['MMSE'].ffill()

In [ ]:
df.isnull().sum()

In [ ]:
df.head(30)

# zscore 

In [ ]:
stats.zscore(df['MMSE'])

In [ ]:
stats.zscore(df['CDR'])

In [ ]:
stats.zscore(df['CDR'])

In [ ]:
stats.zscore(df['eTIV'])

In [ ]:
stats.zscore(df['nWBV'])

In [ ]:
stats.zscore(df['ASF'])

# dropping the unwanted attribute

<b>Feature group</b> i.e class is essential for the classification.It's  helps to classify the patient into demented or non demented.BUT this feature does not help us to predict the disease. So we can drop the feature Group.
<br>
<b>Feature SES</b> i.e Socioeconomic status.This amy help to categorise the target on availability of the quality treatement.It might have an indirect effect on the target,but not so important in predicting the disease.

In [ ]:
df=df.drop(columns='Group')
df['M/F']=df['M/F'].replace('M','0')
df['M/F']=df['M/F'].replace('F','1')

In [ ]:
df

# Analyzing the features
<br>
<b>1.M/F:</b> Gender of the target.
<br>
<br>
<b>2.Age:</b>Age of the targe is one of the most important features.As per the study in most of the population the alzheimer's develop  the disease in the age of 64 or above.There is less than of chances of developing the disease in the people of the age group less than 64.After the 65 the chance of developing the Alzheimer's disease increases.
<br>
<br>
<b>3.Educ:</b>Education is a continuous variable potentially correlated with cognitive function and disease progression.
<br>
<br>
<b>4.MMSE:</b>Mini Mental State Examination is a test conducted to check the cognitive impairment.It is set of 11 question which takes about 5 to 10 minutes.The top score for MMSE is 30. Ascore equalt 25 or above is considered as normal.
<br>
<br>
<b>5.CDR:</b>Clinical Dementia Rating is the  feature which evaluates the cognitive,behavioral and functional aspects of the Alzhemier's disease.Rather than the conducting test it makes judgement on 6 different categories based on the available informations.
<br>
<br>
<b>6.eTIV:</b> Estimated total intracranial volume is the measurement of the variations in the premorbid brain size in imaging studies of cerebral structures in Alzheimer disease (AD).Basically, total intracranial volume is found to correlate with the determinant of the transform matrix used to align an image with an atlas. 
<br>
<br>
<b>7.nWBV:</b> Normalize Whole Brain Volume is the measurement which is expressed in percent of all voxels.
<br>
<br>
<b>8.ASF:</b> Atlas Scaling Factor ASF is a one-parameter scaling factor that allows for comparison of the estimated total intracranial volume (eTIV) based on differences in human anatomy


# FUZZY AHP METHOD

# creating pair-wise comparison matrix

Pair-wise comparision matrix in fuzzy are the n*n matrix which is formulated based on the expert's judgement.this matrix will be aggregated and normalized later,


In [3]:
def pairwise(n):
    comparision_matrix=[]
    for i in range(n):
        row=[]
        for j in range(n):
            value=float(input(f"Enter value of pair wise comparision matrix at row {i}, column {j}: "))
            row.append(value)
        comparision_matrix.append(row)
        
    return(comparision_matrix)
                            
            

# fuzzified pairwise comparison matrix

def fuzzified(comparison_matrix):
    n=len(comparison_matrix)
    fuzzy_matrix = np.zeros((n, n, 3))
    for i in range(n):
        for j in range(i + 1, n):
            m = comparison_matrix[i][j]
            l = m - 1
            u = m + 1
            
            fuzzy_matrix[i][j] = [l, m, u]
            fuzzy_matrix[j][i] = [1/u, 1/m, 1/l]
    for i in range(n):
        for j in range(n):
            if(i==j):
                fuzzy_matrix[i][j]=[1,1,1]
    return (fuzzy_matrix)
                    
    
            
    

In [6]:
import numpy as np
def fuzzified(comparison_matrix):
    n = len(comparison_matrix)
    fuzzy_matrix = np.zeros((n, n, 3))

    for i in range(n):
        for j in range(i + 1, n):
            m = comparison_matrix[i][j]
            l = m - 1
            u = m + 1

            fuzzy_matrix[i][j] = [l, m, u]
            if m != 1: 
                fuzzy_matrix[j][i] = [1/u, 1/m, 1/l]
            else:
                fuzzy_matrix[j][i] = [1/u, 1, u]  

    for i in range(n):
        for j in range(n):
            if i == j:
                fuzzy_matrix[i][j] = [1, 1, 1]
    return fuzzy_matrix


In [4]:
comparison=pairwise(5)

Enter value of pair wise comparision matrix at row 0, column 0:  1
Enter value of pair wise comparision matrix at row 0, column 1:  .3333333333
Enter value of pair wise comparision matrix at row 0, column 2:  3
Enter value of pair wise comparision matrix at row 0, column 3:  5
Enter value of pair wise comparision matrix at row 0, column 4:  7
Enter value of pair wise comparision matrix at row 1, column 0:  3
Enter value of pair wise comparision matrix at row 1, column 1:  1
Enter value of pair wise comparision matrix at row 1, column 2:  5
Enter value of pair wise comparision matrix at row 1, column 3:  7
Enter value of pair wise comparision matrix at row 1, column 4:  9
Enter value of pair wise comparision matrix at row 2, column 0:  .3333333333
Enter value of pair wise comparision matrix at row 2, column 1:  .2
Enter value of pair wise comparision matrix at row 2, column 2:  1
Enter value of pair wise comparision matrix at row 2, column 3:  3
Enter value of pair wise comparision matr

In [21]:
fuzzy=fuzzified(comparison)
fuzzy

array([[[ 1.        ,  1.        ,  1.        ],
        [-0.66666667,  0.33333333,  1.33333333],
        [ 2.        ,  3.        ,  4.        ],
        [ 4.        ,  5.        ,  6.        ],
        [ 6.        ,  7.        ,  8.        ]],

       [[ 0.75      ,  3.        , -1.5       ],
        [ 1.        ,  1.        ,  1.        ],
        [ 4.        ,  5.        ,  6.        ],
        [ 6.        ,  7.        ,  8.        ],
        [ 8.        ,  9.        , 10.        ]],

       [[ 0.25      ,  0.33333333,  0.5       ],
        [ 0.16666667,  0.2       ,  0.25      ],
        [ 1.        ,  1.        ,  1.        ],
        [ 2.        ,  3.        ,  4.        ],
        [ 4.        ,  5.        ,  6.        ]],

       [[ 0.16666667,  0.2       ,  0.25      ],
        [ 0.125     ,  0.14285714,  0.16666667],
        [ 0.25      ,  0.33333333,  0.5       ],
        [ 1.        ,  1.        ,  1.        ],
        [ 2.        ,  3.        ,  4.        ]],

       [[ 0.

# geometric mean

In [8]:
def gm(fuzzy):
    n=len(fuzzy)
    a=[]
    gm=np.zeros((n, 3))
    for i in range(n):
        for k in range(3):
          product=1
          for j in range(n):
            product*=abs(fuzzy[i][j][k])
            product=round(product,2)
          gm[i][k]=(product**(1/n))
                
    return gm  

In [9]:
import numpy as np
from decimal import Decimal, ROUND_HALF_UP

def gm(fuzzy):
  n = len(fuzzy)
  a = []
  gm = np.zeros((n, 3))
  for i in range(n):
      for k in range(3):
          product = 1
          for j in range(n):
              product *= abs(fuzzy[i][j][k])
          gm[i][k] = Decimal(product**(1/n)).quantize(Decimal('.01'), rounding=ROUND_HALF_UP)
  return gm


In [10]:
g_mean=gm(fuzzy)
g_mean

array([[2.  , 2.04, 3.03],
       [2.7 , 3.94, 3.73],
       [0.8 , 1.  , 1.25],
       [0.4 , 0.49, 0.61],
       [0.22, 0.25, 0.3 ]])

# Fuzzy weight

In [11]:
def weight(g_mean):
    n=len(g_mean)
    a=[]
    fuzzy_weights = np.zeros((n, 3))
    sum_l=np.sum(g_mean[:, 0])
    sum_m=np.sum(g_mean[:, 1])
    sum_u=np.sum(g_mean[:, 2])
    a.append(sum_u)
    a.append(sum_m)
    a.append(sum_l)
    for i in range(3):
        for j in range(n):
            fuzzy_weights[j,i]=g_mean[j,i]/a[i]
    return(fuzzy_weights)

In [12]:
f_weight=weight(g_mean)
f_weight


array([[0.22421525, 0.2642487 , 0.49509804],
       [0.30269058, 0.51036269, 0.60947712],
       [0.0896861 , 0.12953368, 0.20424837],
       [0.04484305, 0.0634715 , 0.0996732 ],
       [0.02466368, 0.03238342, 0.04901961]])

# defuzzification

In [13]:
def  defuzzy(f_weight):
    n=len(f_weight)
    weight=np.zeros(n)
    for i in range(n):
        l, m, u = f_weight[i]
        weight[i]=(l+m+u)/3
    return weight
    

In [14]:
defuuzy_w=defuzzy(f_weight)


In [15]:
defuuzy_w

array([0.327854  , 0.4741768 , 0.14115605, 0.06932925, 0.03535557])

# criteria weight

In [16]:
def criteria_w(defuzzy_w):
    n=len(defuuzy_w)
    c_weight=np.zeros(n)
    s=0
    for i in range (n):
        s=s+defuzzy_w[i]
    for i in range(n):
        c_weight[i]=defuzzy_w[i]/s
    return c_weight
        

In [17]:
c_weight=criteria_w(defuuzy_w)
c_weight

array([0.3128761 , 0.45251419, 0.13470738, 0.06616197, 0.03374036])

# Ranking


In [18]:
def rank(c_weight):
    rank=np.empty_like(c_weight)
    sorted_indices = np.argsort(c_weight)[::-1]
    rank[sorted_indices] = np.arange(len(c_weight)) + 1
    return rank
            

In [19]:
rank(c_weight)

array([2., 1., 3., 4., 5.])

# FUZZY SYNTHETIC EVALUATION

In [23]:
def criteria():
    c=int(input("enter number of criteria"))
    a=int(input("enter number of attribute"))
    e_matrix=np.zeros((a, c, 3))
    for i in range(a):
        for j in range(c):
            l, m, u = map(float, input(f"Enter fuzzy value (l, m, u) for attribute {i+1} and criteria {j+1}:").split())
            if l <= m <= u:
                e_matrix[i][j] = [l, m, u]
    return e_matrix
            
    
    

In [ ]:
def weight(c_matrix):
    n=c_matrix.shape[1]
    w_matrix=np.zeros(n)
    for i in range(1,n):
        w_matrix[i]=float(input(f"enter the weight for criteria {i}:"))
    return w_matrix
    

In [ ]:
def aggregate(c_matrix,w_matrix):
    n, m, _ = c_matrix.shape
    aggregated_matrix = np.zeros((n, 3))

    for i in range(n):
        for k in range(3):
            for j in range(m):
                aggregated_matrix[i][k] += w_matrix[j] * c_matrix[i][j][k]
    return aggregated_matrix

In [ ]:
a_matrix=aggregate(c_matrix,w_matrix)
a_matrix

In [ ]:
def defuzzy(a_matrix):
    n=a_matrix.shape[0]
    m=a_matrix.shape[1]
    d_matrix=np.zeros(n)
    for i in range(n):
        s=0
        for j in range(m):
            s=s+a_matrix[i,j]
        a=s/m
        d_matrix[i]=a
    return d_matrix 

In [ ]:
defuzzy(a_matrix)

# NON TRANSITIVE RANKING METHOD

In [ ]:
def compare():
    n=int(input("enter the number"))
    a=np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            a[i,j]=float(input(f"enter value for {i} row {j} column"))
    return a 

In [ ]:
c_matrix=compare()

In [ ]:
def  n_trans(c_matrix):
    n=c_matrix.shape[0]
    f=np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            numer=c_matrix[i,j]
            deno=max(c_matrix[i,j],c_matrix[j,i])
            s=numer/deno
            f[j,i]=s
    return(f)
            
            

In [ ]:
n_matrix=n_trans(c_matrix)
n_matrix

In [ ]:
def rank(n_matrix):
    n=n_matrix.shape[0]
    ranks=np.zeros(n,)
    for i in range(n):
        for j in range(n):
            
            ranks[i]=np.min(n_matrix[i,j])
            #print(row_min)
            #ranks[i]=row_min
    return ranks
    

In [ ]:
rankss=rank(n_matrix)


In [ ]:
rankss

In [ ]:
def ranks(rank):
    ranks=np.empty_like(rank)
    sorted_indices = np.argsort(rank)[::-1]
    ranks[sorted_indices] = np.arange(len()) + 1
    return rank

In [ ]:
ranks(rank)